replicaCount: 1

image:
  repositoryDomainMap:
    us-east-2: 940482419867.dkr.ecr.us-east-2.amazonaws.com
    eu-north-1: 495599756225.dkr.ecr.eu-north-1.amazonaws.com
    eu-central-1: 816069136154.dkr.ecr.eu-central-1.amazonaws.com
    us-east-1: 463470961310.dkr.ecr.us-east-1.amazonaws.com
    ap-northeast-1: 248189928082.dkr.ecr.ap-northeast-1.amazonaws.com
    ap-southeast-2: 495599779797.dkr.ecr.ap-southeast-2.amazonaws.com
    ap-south-1: 183295424886.dkr.ecr.ap-south-1.amazonaws.com
    eu-west-1: 741448945724.dkr.ecr.eu-west-1.amazonaws.com
    sa-east-1: 985539796278.dkr.ecr.sa-east-1.amazonaws.com
    us-west-1: 034362067326.dkr.ecr.us-west-1.amazonaws.com
    ap-southeast-1: 235494799058.dkr.ecr.ap-southeast-1.amazonaws.com
    us-west-2: 586794468202.dkr.ecr.us-west-2.amazonaws.com
    eu-west-2: 869935108213.dkr.ecr.eu-west-2.amazonaws.com
    ap-southeast-4: 872515262625.dkr.ecr.ap-southeast-4.amazonaws.com
    ap-southeast-3: 112551748145.dkr.ecr.ap-southeast-3.amazonaws.com
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""


serviceAccount:
  create: true
  annotations: {}
  name: sagemaker-hyperpod-usage-report-service-account

rbac:
  create: true
