{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sagemaker-hyperpod-usage-report.fullname" . }}
rules:
  - apiGroups: ["kueue.x-k8s.io"]  # API group for ClusterQueue
    resources: ["clusterqueues", "workloads"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]  # Core API group (for Namespaces and Pods)
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]  # "" indicates the core API group
    resources: ["nodes"]
    verbs: ["get"]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sagemaker-hyperpod-usage-report.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sagemaker-hyperpod-usage-report.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sagemaker-hyperpod-usage-report.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
