{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sagemaker-hyperpod-usage-report.serviceAccountName" . }}
  namespace: {{ include "sagemaker-hyperpod-usage-report.namespace" . }}
  labels:
    {{- include "sagemaker-hyperpod-usage-report.labels" . | nindent 4 }}
{{- end }}
